---
title: "Model-debug"
output: rmarkdown::html_vignette
description: >
  How to debug models
contents:
 - starts_with("ingest_")
vignette: >
  %\VignetteIndexEntry{Model-debug}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  eval = FALSE,
  comment = "#>"
)
```

> A set of code chunks, procedures, and utilities for a RRASSLER execution.

## Model debug helper

```{r, eval=FALSE}
geom_path="G:/data/ras_catalog/_temp/BLE/12090301/12090301_models/Model/Walnut Creek-Colorado River/CEDAR CREEK/CEDAR CREEK.g01"
units="Foot"
proj_string="EPSG:2277"
in_epoch_override = as.integer(as.POSIXct(Sys.time()))
out_epoch_override = as.integer(as.POSIXct(Sys.time()))
vdat_trans=FALSE
quiet=FALSE
default_g=FALSE
try_both=TRUE
# extrated_pts <- parse_model_to_xyz(geom_path=geom_path,
#                                    units=units,
#                                    proj_string=proj_string,
#                                    in_epoch_override = as.integer(as.POSIXct(Sys.time())),
#                                    out_epoch_override = as.integer(as.POSIXct(Sys.time())),
#                                    vdat_trans=vdat_trans,
#                                    quiet=quiet,
#                                    default_g=default_g,
#                                    try_both=try_both)
extrated_pts <- try({
  parse_model_to_xyz(geom_path=geom_path,
                     units=units,
                     proj_string=proj_string,
                     in_epoch_override = as.integer(as.POSIXct(Sys.time())),
                     out_epoch_override = as.integer(as.POSIXct(Sys.time())),
                     vdat_trans=vdat_trans,
                     quiet=quiet,
                     default_g=default_g,
                     try_both=try_both)
})
if(nrow(extrated_pts[[1]])==0){
  current_initial_name <- paste0("unknown_",current_model_name,"_",current_g_value,"_",current_last_modified)
  current_final_name_key <- NA

  if(sum(stringr::str_detect(na.omit(ras_catalog_dbase$initial_scrape_name), current_initial_name)) == 0) {
    new_row <- data.table::data.table(current_nhdplus_comid,
                                      current_model_name,
                                      current_g_value,
                                      current_last_modified,
                                      code_to_place_in_source,
                                      current_model_units,
                                      current_model_projection,
                                      current_initial_name,
                                      current_final_name_key,
                                      "unparsed_units_proj")
    names(new_row) <- names
    ras_catalog_dbase <- data.table::rbindlist(list(ras_catalog_dbase,new_row))

    dir.create(file.path(path_to_ras_dbase,"models","_unprocessed",current_initial_name,fsep = .Platform$file.sep), showWarnings = FALSE, recursive = TRUE)
    file.copy(c(g_file ,paste0(g_file,".hdf") ,p_files ,f_files ,h_files, v_files, prj_files,o_files,r_files,u_files,x_files,rasmap_files),
              file.path(path_to_ras_dbase,"models","_unprocessed",current_initial_name,fsep = .Platform$file.sep))
    data.table::fwrite(ras_catalog_dbase,file.path(path_to_ras_dbase,"accounting.csv",fsep = .Platform$file.sep), row.names = FALSE)
    process_count = process_count + 1
  } else {
    if(!quiet) { print("Model with inital scrape name already in the que") }
    duplicate_count = duplicate_count + 1
  }
  next()
}

# Footprint the points we extracted
ls = sfheaders::sf_linestring(
  obj = extrated_pts[[1]]
  , x = "x"
  , y = "y"
  # , z = "z"
  , linestring_id = "xid"
  , keep = FALSE
) |> sf::st_set_crs(sf::st_crs("EPSG:6349"))
#
if(quick_hull) {
  end_points <- c(ls %>% lwgeom::st_endpoint(), ls %>% lwgeom::st_startpoint())
  end_points <- sf::st_coordinates(end_points) %>%
    as.data.frame(extrated_pts[[1]]) %>%
    dplyr::group_by(X,Y) %>%
    dplyr::distinct() %>%
    sf::st_as_sf(coords = c("X","Y")) %>%
    sf::st_set_crs(sf::st_crs("EPSG:6349")) %>%
    sf::st_transform(sf::st_crs("EPSG:4326"))
} else {
  end_points <- sf::st_coordinates(ls) %>%
    as.data.frame(extrated_pts[[1]]) %>%
    dplyr::group_by(X,Y) %>%
    dplyr::distinct() %>%
    sf::st_as_sf(coords = c("X","Y")) %>%
    sf::st_set_crs(sf::st_crs("EPSG:6349")) %>%
    sf::st_transform(sf::st_crs("EPSG:4326"))
}

ahull_poly = holyhull::holyhull(sf_frame=end_points, method='convave', alpha_value=0.01, concavity = 2, length_threshold = 0)

flowline_list <- try({
  nhdplusTools::get_nhdplus(AOI::aoi_get(ahull_poly),realization = "flowline")
})

# Join to comids
if(length(flowline_list) == 0) {
  current_nhdplus_comid = 2
} else {
  current_nhdplus_comid = flowline_list[flowline_list$streamorde == max(flowline_list$streamorde),][1,]$comid
}
```

## Proj finder
```{r, eval = FALSE}
path_to_gdb <- file.path("G:/data/ras_catalog/_temp/BLE/12030109/12030109_SpatialData/12030109_Chambers.gdb")
fc <- rgdal::readOGR(dsn=path_to_gdb,layer="BLE_DEP01PCT")
print(sf::st_crs(fc))
```

## RAS zip scraper
```{python, python.reticulate = FALSE, eval = FALSE}
import argparse
import tarfile
import os
from pathlib import Path
# file="C:\Users\rdp-user\Projects\data\ras_models\_temp\IFC\07020009.tar.gz"
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
def unpacker(str_huc8_arg,str_tar_file):
    str_out_dir = os.path.join(os.path.dirname(str_tar_file),str_huc8_arg)
 
    if not os.path.exists(str_tar_file):
        print('File does not exist?')
        print(str_tar_file)
        return
        
    if os.path.exists(str_out_dir):
        print('File already unpacked')
        return
    
    os.mkdir(str_out_dir)

    # read the tar.gz file... this takes some time
    t = tarfile.open(str_tar_file, "r:gz")

    for member in t.getmembers():
        if member.name[-3:-2] == 'g' or member.name[-3:-2] == 'p' or member.name[-3:-2] == 'f' or member.name[-3:-2] == 'h' or member.name[-3:-2] == 'v':
            #print(member.name)
            t.extract(member, str_out_dir)

    print(" Done ")
    return

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='========== IFC by (HUC8) ==========')

    parser.add_argument('-w',
                        dest = "str_huc8_arg",
                        help = 'REQUIRED: HUC-8 watershed that is being evaluated: Example: 10170204',
                        required = True,
                        type = str)  # has to be string so it doesn't strip the leading zero

    parser.add_argument('-i',
                        dest = "str_tar_file",
                        help = r'OPTIONAL: path containing the HEC_RAS files: Example -i C:\HEC\input_folder\my_models.' \
                               r' Defaults to c:\ras2fim_datas\OWP_ras_models\models.',
                        required = False,
                        type = str)
    
    args = vars(parser.parse_args())
    
    unpacker(**args)
```
